name: CD Develop
on:
  push:
    branches: [ develop ]
jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USER_MASTER_PROD }}
          host: ${{ secrets.HOST_MASTER_PROD }}
          key: ${{ secrets.KEY_MASTER }}
          port: 22
          script: '/root/projects/xp/deploy_dashv2.sh'
